### ISSUE TITLE
Drop support for old pythons and tox

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#11]
In order to ease development and maintenance of the project, I would like to propose requiring `python>=3.6` and `tox>=3.x.y`, where exact version is determined based on which feature we need to make use of from tox.

Recent versions of tox also got support for bootstrapping itself newer versions, making much easier to run itself without having to worry about: what if the used does not have a recent enough tox.

**Comment by greg-hellings** [comment]
My only requirement is that the version we run on be sufficient to run in RHEL 7, which is where we do half of our testing with it. I'm not trying to specifically require older versions of the code - working all the way back to tox 2.7 was just me experimenting with how far back the test suite would pass. It worked back to 2.4 until we added descriptions, at which 2.7 became the minimum passing version.

So, really, those minimum versions are just "It does work here" and not a guarantee of "It must work here". If there's a reason we need to bump to newer, I'm not against that, as long as it still works with the Pythons available for RHEL.

**Comment by ssbarnea** [comment]
RHEL 7.8 comes with python3.6 but you still need to install tox using pip if you want a decent version. That is what we do with tripleo. In fact the same requirements apply to molecule 3.x.

I should also remark the fact that this requirement does not apply to the python used by tox virtualenvs. AFAIK, they could even be py2x.

For tox version I think is ok to keep an older version tested and bump it when we need, like we needed with description.

**Comment by greg-hellings** [comment]
We're running Molecule 3, and I know we're at least in RHEL 7.8 (looking at the Jenkins instance, it might even be RHEL 8). So I'm OK with dropping the Python 2.7 requirements if it's holding us back from something. Tox, I'm not under any particular need to keep it anything old, I just was avoiding premature optimization on that end.

**Comment by greg-hellings** [comment]
Going to close this since we've converted to Python 3.6+ and we're not holding a strong line on tox versions, either.
