### ISSUE TITLE
Document a live communication channels between cores

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#14]
I would like to suggest using a live chat medium to get in sync between cores, as we can make quick decisions faster than using offline.

How about reusing #ansible-molecule freenode channel? The channel does not have so much traffic and it can also be an opportunity to advertise tox-ansible to other molecule users. 

My freenode nick is @zbr` (also mentioned in my github profile).

**Comment by greg-hellings** [comment]
I'm cool with IRC. Most projects I work with have a channel on there. My nick is GHellings
