### ISSUE TITLE
Avoid false positive scenario detection

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#25]
I recently discovered that tox-ansible seems to be too eager to detect scenarios even when it should not. Try to clone https://github.com/ansible-community/molecule-azure/ and run a `tox -al` after installing the plugin.

This project does not have any real molecule scenarios inside it, still you get a huge list of false positive, including some looking as:
```
py27-lib-site-packages-test-scenarios-cleanup-default
py27-lib-site-packages-test-scenarios-dependency-ansible-galaxy
py27-lib-site-packages-test-scenarios-dependency-gilt
```

My guess is that it is looking inside `.tox` folder when it should not. To avoid this I used another discovery logic on https://github.com/ansible/ansible-lint/blob/de48ef920c55f74baec394a95276d060f87b955b/lib/ansiblelint/utils.py#L675 -- which avoided me having to implement include/exclude lists.

PS. Adding a hardcoded .tox skip would be a first step, much easier and safer to implement.

**Comment by greg-hellings** [comment]
So the new changes do traverse all directories, including .tox if it is present, using os.walk.

You can currently ignore that by putting this segment into tox.ini:
```ini
[ansible]
ignore_path =
    .tox
```

I've considered changing to `glob.glob('**/molecule/*/molecule.yml', recursive=True)`. Pros: faster. Cons: ignores all `.foo` directories by default. I think I'm OK with ignoring .named directories.

**Comment by ssbarnea** [comment]
I am ok too with default ignore of dots, much better than asking users to add extra config to each repository, especially as tox-ansible is usually installed as a development tool, so directly affecting any tox project you may have on the same machine.
