### ISSUE TITLE
Neither file bindep.txt nor file other-requirements.txt exist.

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#32]
Apparently trying to run tox-ansible with the only existing scenario from https://github.com/openstack/tripleo-ci is causing a failure like:
```
$ tox -e roles-tripleo-repos-default                                                                               [9:45:46]
GLOB sdist-make: /Users/ssbarnea/c/opendev/tripleo-ci/setup.py
roles-tripleo-repos-default create: /Users/ssbarnea/c/opendev/tripleo-ci/.tox/roles-tripleo-repos-default
roles-tripleo-repos-default installdeps: -r/Users/ssbarnea/c/opendev/tripleo-ci/test-requirements.txt, -r/Users/ssbarnea/c/opendev/tripleo-ci/requirements.txt
roles-tripleo-repos-default develop-inst: /Users/ssbarnea/c/opendev/tripleo-ci
roles-tripleo-repos-default installed: ...
roles-tripleo-repos-default run-test-pre: PYTHONHASHSEED='1563349172'
roles-tripleo-repos-default run-test-pre: commands[0] | pip install -q bindep
roles-tripleo-repos-default run-test-pre: commands[1] | bindep test
Neither file bindep.txt nor file other-requirements.txt exist.
ERROR: InvocationError for command /Users/ssbarnea/c/opendev/tripleo-ci/.tox/roles-tripleo-repos-default/bin/bindep test (exited with code 1)
__________________________________________________________ summary __________________________________________________________
ERROR:   roles-tripleo-repos-default: commands failed
```

This is caused by the fact that the project has `commands_pre` configured on default environment. I suspect that this plugin is changing the current working directory to match the scenario one with the undesired side-effect of messing the commands_pre.

Probably the first measure would be to override commands_pre in our virtual tox environment with a nop command.

**Comment by ssbarnea** [comment]
After checking current implementation I see that current behavior is to keep commands defined in root testenv. IMHO, this plugin should ignore both `commands` and `commands_pre` from root test env and only call molecule.

We should keep molecule environments as isolated as possible from normal tox environments, or we will get into conflicts.

@geerlingguy What do you think about this? I can easily change this but I am not sure about impact on your existing use cases.

**Comment by greg-hellings** [comment]
If it is honoring commands from the root testenv then it's not behaving the way I intended. I intended for it to override root values but not one from testenv:foo if it's already defined. I didn't touch commands_pre at all.

Changing to inherit from a specific testenv is OK by me and helps give explicit isolation. My existing cases do not define anything around commands, deps, or the rest of the fields this plugin defines so there should not be any impact on my tests by such a change

**Comment by ssbarnea** [comment]
The default behavior of tox is to silently copy settings from default env, when you do not define them. You do not need to do anything for this to happen.

I already fixed the commands_pre locally and I will propose a patch soon. I will wait for you to review and test to avoid possible regressions.

Now I was busy creating a tox-report plugin :D

**Comment by ssbarnea** [comment]
I am closing this because it looks more like a user specific issue related to the chdir. It can be avoided by converting the command to chained shell variant like `basic -c "cd correct_folder && command"`.

At this moment I am not sure if there is something tox-ansible can do to improve this because the commands run by it may need different chdir while the ones defined by the user in defaults may assume another directory.
