### ISSUE TITLE
Implement stricter coding standards

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/tox-ansible#5]
Current lint is limited to running "flake8" on the codebase. We should implement more stringent rules. Suggestions and implementations welcome.

**Comment by greg-hellings** [comment]
@ssbarnea - I think we can close this, now? Between the two sets of pre-commit updates, the codebase is well and thoroughly standardized now, I think.

**Comment by ssbarnea** [comment]
👍-- i still want to enable pylint and mypy but later, after we require py36.
