### ISSUE TITLE
1.0.0 installs broken molecule

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/tox-ansible#54]
Version 1.0.0 somehow installs a version of molecule that is broken and won't run at all. It simply exits silently with return code of "1".

**Comment by greg-hellings** [comment]
Git bisect tells me that this error was introduced with commit 533f1cb78ec7fe579404ac4bc19efbbe039db9c1. Beginning investigation into that, now.

**Comment by greg-hellings** [comment]
Nope. That's just the first commit, with the change to subprocess.run, that allows my test code to identify that there IS an error. There's something else going on around here.

**Comment by btravouillon** [comment]
Hi @greg-hellings,

I hit a similar issue where molecule exits with rc=1. I nailed it to rich 9.5.0 and commit https://github.com/willmcgugan/rich/commit/12b268d223d2f4eed77f5d88ef875be4dfdc2170.
[enrich](https://pypi.org/project/enrich/#history) 1.2.3 is not compatible with this change.

**Comment by btravouillon** [comment]
https://github.com/ansible-community/molecule/issues/3010

**Comment by greg-hellings** [comment]
With your help I've added #55 to hopefully address this issue. Once enrich is updated, we can pin a minimum version onto that.
